### ISSUE TITLE
Duplicate entry for username

### ISSUE THREAD

**Issue by dotmiikee** [Adldap2/Adldap2-Laravel#579]
- Laravel Version: Latest
- Adldap2-Laravel Version: Latest
- PHP Version: 7.2
- LDAP Type: Active Directory
- MYSQL Version: 8

### Description:

For some reason, if a user already exists in the user's table it fails to log them in with the above SQL constraint violation. This is when I'm using MySQL.

`"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'MYUSERNAME' for key 'users_username_unique' (SQL: insert into users (username, name, ▶"`

**Comment by dotmiikee** [comment]
I created a new issue for this as it was tied in with another open issue I had. However; I seem to have found the fix or a workaround?

I changed the script to authenticate using the USERNAME instead of EMAIL. Following the "Build from Scratch" instructions. I renamed the email field to username in the migration script. However; when the migration runs it adds a UNIQUE index on the username column that is created. 

By removing the UNIQUE index from this column the script is able to login appropriately. However, I wanted to verify this is how it should be or if others have the UNIQUE index on their username column. 

Thoughts?

**Comment by dotmiikee** [comment]
Nevermind, by removing the UNIQUE index from the username field causes the application to create a new user entry everytime you login. Still investigating for root cause.

**Comment by dotmiikee** [comment]
Below is a snippet from the log when I try to login. Isn't it strange that the log states that the User has been successfully synchronized and then it throws an error stating that it can't insert into the columns?

*****************************************************************

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' has been successfully found for authentication.`

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' is being imported.  `

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' is being synchronized.`  

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' has been successfully synchronized.  `

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' is authenticating with username: 'CN=COMMON NAME,OU=CORP,OU=Users,DC=domain,DC=com'  `

`[2018-08-23 06:16:47] local.INFO: User 'COMMON NAME' has successfully passed LDAP authentication. ` 

`[2018-08-23 06:16:47] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'USERNAME' for key 'username' (SQL: insert into `users` (`username`, `name`, `memberof`, `password`, `updated_at`, `created_at`) values (username, COMMON NAME, CN=GroupName,OU=ou1,OU=ou2,OU=ou3,OU=ou4,DC=domain,DC=com, hashed password, 2018-08-23 06:16:47, 2018-08-23 06:16:47))`

**Comment by dotmiikee** [comment]
Still digging, but it seems to throw the exception when it hits **$model->save();** in the validateCredentials function within the DatabaseUserProvider.php

     public function validateCredentials(Authenticatable $model, array $credentials)
            {
            if ($this->user instanceof User) {
                // If an LDAP user was discovered, we can go
                // ahead and try to authenticate them.
               if (Resolver::authenticate($this->user, $credentials)) {
                   Event::fire(new AuthenticatedWithCredentials($this->user, $model));

                // Here we will perform authorization on the LDAP user. If all
                // validation rules pass, we will allow the authentication
                // attempt. Otherwise, it is automatically rejected.
                if ($this->passesValidation($this->user, $model)) {
                    // Here we can now synchronize / set the users password since
                    // they have successfully passed authentication
                    // and our validation rules.
                    Bus::dispatch(new SyncPassword($model, $credentials));

                    //dd(Bus::dispatch(new SyncPassword($model, $credentials)));

                   $model->save();


                    if ($model->wasRecentlyCreated) {
                        // If the model was recently created, they
                        // have been imported successfully.
                        Event::fire(new Imported($this->user, $model));
                    }

                    Event::fire(new AuthenticationSuccessful($this->user, $model));

                    return true;
                }

                Event::fire(new AuthenticationRejected($this->user, $model));
            }

            // LDAP Authentication failed.
            return false;
        }

        if ($this->isFallingBack() && $model->exists) {
            // If the user exists in our local database already and fallback is
            // enabled, we'll perform standard eloquent authentication.
            return $this->fallback->validateCredentials($model, $credentials);
        }

        return false;
        } 



If I do a dump and die just before it
**dd(Bus::dispatch(new SyncPassword($model, $credentials)));**
 I get the following User model array. 

````User {#741 ▼
  #fillable: array:3 [▼
    0 => "name"
    1 => "username"
    2 => "password"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: null
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: false
  +wasRecentlyCreated: false
  #attributes: array:4 [▼
    "username" => "myusername"
    "name" => "commonname"
    "memberof" => "CN=groupname,OU=subOU,OU=Groups,DC=domain,DC=com"
    "password" => "hashed password"
  ]
  #original: []
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▼
    0 => "*"
  ]
  #rememberTokenName: "remember_token"
}````

**Comment by dotmiikee** [comment]
It seems that script doesn't believe the model exists in the database. So there for it's jumping to **$saved = $this->performInsert($query);**. I just cannot find where or why this is happening. 

    C:\inetpub\hero\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php
        // If the "saving" event returns false we'll bail out of the save and return
        // false, indicating that the save failed. This provides a chance for any
        // listeners to cancel save operations if validations fail or whatever.
        if ($this->fireModelEvent('saving') === false) {
            return false;
        }
 
        // If the model already exists in the database we can just update our record
        // that is already in this database using the current IDs in this "where"
        // clause to only update this model. Otherwise, we'll just insert them.
        if ($this->exists) {
            $saved = $this->isDirty() ?
                        $this->performUpdate($query) : true;
        }
 
        // If the model is brand new, we'll insert it into our database and set the
        // ID attribute on the model to the value of the newly inserted row's ID
        // which is typically an auto-increment value managed by the database.
        else {
            $saved = $this->performInsert($query);
 
            if (! $this->getConnectionName() &&
                $connection = $query->getConnection()) {
                $this->setConnection($connection->getName());
            }
        }
 
        // If the model is successfully saved, we need to do a few more things once
        // that is done. We will call the "saved" method here to run any actions
        // we need to happen after a model gets successfully saved right here.
        if ($saved) {
            $this->finishSave($options);
        }
 
        return $saved;

**Comment by adaroobi** [comment]
I know this might be late but might help clarify the reason behind the cause since I've stumble upon this case today due to case mismatch since LDAP's attributes are mostly case insensitive.

e.g:
LDAP sAMAccountName: M.Dave
Authentication input: m.dave
First time authenticate will succeed and will save sAMAccountName or whatever attribute defined in 'ldap_auth.usernames.ldap.authenticate' config. So your database should have the cased version 'M.Dave' Next time attempt will fail the existence evaluation in database and promote to import from LDAP as a new record and here where integrity error will raise and interrupt the process.

I'll try to submit a pull request regarding this issue which I solved by (lowercasing) the evaluated credentials when attempted to authenticate.

**Comment by stevebauman** [comment]
Hi guys, I'm able to reproduce this as well using usernames. Patch is coming out shortly!

**Comment by stevebauman** [comment]
Scratch that, not fixed yet. Discovered more cases with this when LDAP records themselves have alternative casing as well.

**Comment by stevebauman** [comment]
Okay, now fixed in [v5.1.1](https://github.com/Adldap2/Adldap2-Laravel/releases/tag/v5.1.1).

**Comment by adaroobi** [comment]
You're awesome! Just to note that you need to resync the stored users (if any affected) upon update in order to fulfill with the new store method.

**Comment by stevebauman** [comment]
Thanks @adaroobi! :smile: Let me know if you run into any further issues.

**Comment by adaroobi** [comment]
No worries 😄

**Comment by jlsjonas** [comment]
This seems to clash with [your comment](https://github.com/Adldap2/Adldap2-Laravel/issues/542#issuecomment-385402769) on #542 implying you wouldn't implement string conversion.

The `strtolower` added to `Import.php` is breaking compatibility with our system as our convention has all usernames uppercased everywhere. and further relations are made based on username in our database (relation with legacy/external systems that don't have the user_id itself)

**Comment by stevebauman** [comment]
Hi @jlsjonas, this change was modified in the latest major release v6.0 but exists in the latest v5.1 version:

## v6.0

https://github.com/Adldap2/Adldap2-Laravel/blob/9f211dc8f9213e185fc8bb2db79faf836513d9d7/src/Commands/Import.php#L83-L94

## v5.1

https://github.com/Adldap2/Adldap2-Laravel/blob/31f80dfad6950f80698986e91cb65eb0c441f182/src/Commands/Import.php#L95-L101

If you like, we can patch the v5.1 branch to fix this issue and have it configurable, or you can use the new v6.0 which should solve your issue.

It's hard to identify what requirements certain users need, so I appreciate you commenting and letting me know that this causes issues for you.

**Comment by jlsjonas** [comment]
> It's hard to identify what requirements certain users need, so I appreciate you commenting and letting me know that this causes issues for you.

You're welcome, I understand how hard it can be to take into account all users' requirements.

>If you like, we can patch the v5.1 branch to fix this issue and have it configurable, or you can use the new v6.0 which should solve your issue.

I noticed that 6 didn't have the strtolower at that point anymore but didn't have enough time to see if it had just moved instead. Already in the process of upgrading to 6.0 meanwhile. 😄

Thanks for the clarifications & the work!
