### ISSUE TITLE
Incompatibility with PHP 7.4 (ldap_control_paged_result() is deprecated)

### ISSUE THREAD

**Issue by papalardo** [Adldap2/Adldap2-Laravel#838]
- Laravel Version: 6.0
- Adldap2-Laravel Version: 6.0
- PHP Version: 7.4
- LDAP Type: ActiveDirectory

### Description: I have a problem when trying import users.

```bash
❯ php artisan adldap:import

   ErrorException  : Function ldap_control_paged_result() is deprecated

  at /Users/../vendor/adldap2/adldap2/src/Connections/Ldap.php:397
    393|      * {@inheritdoc}
    394|      */
    395|     public function controlPagedResult($pageSize = 1000, $isCritical = false, $cookie = '')
    396|     {
  > 397|         return ldap_control_paged_result($this->connection, $pageSize, $isCritical, $cookie);
    398|     }
    399| 
    400|     /**
    401|      * {@inheritdoc}

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Function ldap_control_paged_result() is deprecated", "/Users/.../vendor/adldap2/adldap2/src/Connections/Ldap.php", [""])
      /Users/.../vendor/adldap2/adldap2/src/Connections/Ldap.php:397

  2   Adldap\Connections\Ldap::controlPagedResult("")
      /Users/.../vendor/adldap2/adldap2/src/Query/Builder.php:494

  Please use the argument -v to see more details.
```

When will have support to PHP 7.4 ??

**Comment by stevebauman** [comment]
Hi @papalardo,

This has been resolved in the new core repository [LdapRecord](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.1.3). I will be updating this in the coming days for PHP 7.4 support.

**Comment by papalardo** [comment]
Thanks @stevebauman  for spend your time and efforts to update this package.

**Comment by KarimGeiger** [comment]
Thanks, @stevebauman! Really appreciated. Looking forward to the new release!

**Comment by KarimGeiger** [comment]
Hi @stevebauman, as far as I can tell this issue is still to be resolved, right? Is there any way we can help you with it? We currently `@`-ed the corresponding calls and don't feel good about it, so we'd love to get a resolution on this.

**Comment by stevebauman** [comment]
Hi @KarimGeiger,

[v10.3.0](https://github.com/Adldap2/Adldap2/releases/tag/v10.3.0) contains a patch for this. Have you ran `composer update`?

 Closing this, as this is resolved, but feel free to comment back if you’re not receiving the new version.

**Comment by KarimGeiger** [comment]
Oh, I was checking the changelog for the wrong packages apparently, sorry. Thanks for resolving this, much appreciated!
